### ISSUE TITLE
default date is incorrect

### ISSUE THREAD

**Issue by DronHazra** [wwsalmon/updately#71]
noticed a bug with how my updates very unambiguously written on a certain evening (e.g. sep 12) are given the date "sept 13". i am working on this btw

**Comment by DronHazra** [comment]
i have a feeling it has to do with how the date field is populated... maybe some timezone issue or something?

**Comment by DronHazra** [comment]
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/62195614/191155225-d16e9917-c3e4-44e0-9c90-103401cd6ef6.png">

**Comment by DronHazra** [comment]
this error isn't reproduced on localhost, which leads me to believe its something to do with the server timezone.

**Comment by DronHazra** [comment]
yup, the problem is with the new draft system — the `new Date()` constructor is run on the server (to create a draft) and thus initializes the date string (which doesn't include time information, it's only date) based on the timezone the server is in, not the timezone the user is in.

**Comment by wwsalmon** [comment]
fixed in #72
