### ISSUE TITLE
dark mode on activity grid

### ISSUE THREAD

**Issue by laurgao** [wwsalmon/updately#89]
the year labels are ugly in dark mode (highlighted year should be a lighter color than the others) 

![image](https://github.com/wwsalmon/updately/assets/47482178/9d49aac6-dea0-42a8-a553-a0fa95ea8d5e)

for comparison, light mode is prettier:

![image](https://github.com/wwsalmon/updately/assets/47482178/8cf566ff-a70f-4d8e-99ea-fb84d6b2f7cf)

**Comment by DronHazra** [comment]
<img width="893" alt="image" src="https://github.com/wwsalmon/updately/assets/62195614/c3d4e8a8-5a1b-43af-88ef-f22a332186af">
#94 made this much worse

**Comment by wwsalmon** [comment]
oh LOL
